### ISSUE TITLE
Simplify UI with routing

### ISSUE THREAD

**Issue by tmoutinho** [1Hive/vesting-app#15]
We should simplify the UI with views to each elements.

- [ ] Add view for all vestings ( filters ? )
- [ ] Add view for all my vestings history ( filters? )
- [ ] Add FAQ view

PR
https://github.com/1Hive/vesting-app/pull/17

**Comment by kamikazebr** [comment]
Yeah view with filters so good approach, filters like only show active vesting, or "created by me" and etc.
